name: Build and Deploy Angular App

on:
  workflow_call:
    inputs:
      build-config:
        required: true
        type: string
        description: 'Angular build configuration'
      server-path:
        required: true
        type: string
        description: 'Server path for deployment'
    secrets:
      HOST:
        required: true
      USER:
        required: true
      SSH_KEY:
        required: true

jobs:
  build-and-deploy:
    name: Build and Deploy Angular App
    runs-on: ubuntu-latest
    environment: front

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Angular app
        run: npm run build -- --configuration=${{ inputs.build-config }}

      - name: Clean old dist on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: rm -rf ${{ inputs.server-path }}/*

      - name: Upload dist to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: dist/browser/*
          target: ${{ inputs.server-path }}/
