name: Deploy to TEST

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Specific commit SHA (optional, leave empty for latest)'
        required: false
        type: string

jobs:
  deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      branch: 'develop'
      build-config: 'test'
      server-path: '/var/www/megatest'
      commit_sha: ${{ inputs.commit_sha }}
    secrets:
      HOST: ${{ secrets.HOST }}
      USER: ${{ secrets.USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
